### ISSUE TITLE
Question about this project

### ISSUE THREAD

**Issue by Eric24** [JasonRJ/RAK7200_Helium_Mapper#2]
Hi Robert--
I'm trying to understand the nature of this project. Did you just use the RAK7200 hardware and write entirely new firmware or did you start with firmware from RAK and modify it?
--Eric

**Comment by JasonRJ** [comment]
Hi Eric,

Yes the project uses the RAK7200 hardware and replaces the RAK installed firmware with custom firmware built using the Arduino platform.

Robert

**Comment by Eric24** [comment]
@JasonRJ - Ah, makes sense now. From a post I saw on the RAK forum that referenced your project, it made it seem like RAK had open-sourced their RAK7200 firmware.

So you essentially created the current code included in this repo by reverse-engineering the RAK7200 hardware? Are you planning on doing any work with the "external" I2C sensors (LI3DH, etc.)?
